const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
if(new URLSearchParams(location.search).has('native')){$('#game').outerHTML='<div class="native-placeholder" style="height:55vh;display:grid;place-content:center;border:1px solid #3a4234;border-radius:6px;padding:32px;text-align:center"><h2>原生游戏窗口</h2><p class="muted">此控制台仅连接原生实例，不启动第二个 Web 游戏。<br>在 Godot 中运行工程，或启动已导出的 macOS 应用。</p></div>'}else{$('#game').src='/play/index.html'}
const names={green:'苔绿侦察队',blue:'钴蓝机动队',red:'砖红守备队'}, colors={green:'#91ac76',blue:'#79a8bb',red:'#bc7b67'};
const actions={grenade:"投掷手雷",capture:'占领中央目标',cover:'寻找方向掩体',flank:'向侧翼推进',retreat:'撤回出生阵地',hold:'原地防守',move:'移动到指定位置',attack:'攻击指定目标'};
const modes={game_ai:'游戏 AI',player:'玩家接管',agent:'外部 Agent'},states={idle:'待机',move:'移动',cover:'掩护',aim:'瞄准',fire:'射击',reload:'换弹',suppressed:'受压制',dead:'失去战斗力',melee:'刺刀近战'};
const phases={take_cover:'占据掩体',suppress:'建立压制',bound:'交替推进',advance:'队形行军',retreat:'撤退'};
const roles={overwatch:'火力掩护',assault:'突击',anti_armor:'反装甲',armor:'装甲支援'},stances={open:'开阔',hide:'隐蔽',peek:'探头',crouch:'低姿'},orders={formation:'队形移动',bound:'掩护推进',cqb_flank:'绕侧清理',reverse:'倒车脱离',reposition:'调整站位',fire_support:'定点支援',retreat:'撤退',overwatch:'掩护',take_cover:'入位',hold:'待命'};
let state={},live=false,team='green',toastTimer,pendingId=null,lastFactions='';
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3000)}
async function command(c){try{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({faction:team,...c})});const d=await r.json();if(!r.ok)throw Error(d.error);pendingId=d.id;$('#receipt').textContent='指令已排队，等待引擎回执…';return d}catch(e){toast('指令未执行：'+e.message)}}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function clock(t){return `${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`}
function factions(){const key=JSON.stringify([team,state.control,state.units?.map(u=>[u.id,u.hp>0])]);if(key===lastFactions)return;lastFactions=key;$('#factions').innerHTML=Object.keys(names).map(t=>`<div class="faction ${t===team?'selected':''}" data-team="${t}"><div class="faction-line"><b style="color:${colors[t]}">● ${names[t]}</b><span>${state.units.filter(u=>u.faction===t&&u.hp>0).length} UNITS</span></div><select aria-label="${names[t]}控制方式" data-team="${t}">${Object.entries(modes).map(([k,v])=>`<option value="${k}" ${state.control[t]===k?'selected':''}>${v}</option>`).join('')}</select></div>`).join('');$$('.faction').forEach(el=>el.onclick=e=>{if(e.target.tagName!=='SELECT'){team=el.dataset.team;render()}});$$('.faction select').forEach(el=>el.onchange=()=>{team=el.dataset.team;command({action:'control',mode:el.value})})}
function drawMap(){const canvas=$('#map'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,b=state.bounds;if(!b)return;const point=p=>[(p[0]-b[0])/(b[2]-b[0])*w,(p[1]-b[1])/(b[3]-b[1])*h];ctx.clearRect(0,0,w,h);ctx.fillStyle='#1c281f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#2d3a2b';ctx.lineWidth=1;for(let x=0;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
for(const c of [...state.covers,...state.obstacles]){const p=point(c.position),sw=c.size[0]/(b[2]-b[0])*w,sh=c.size[1]/(b[3]-b[1])*h;ctx.fillStyle=c.alive===false?'#393b2b':c.kind==='sandbag'?'#8a7c51':'#46523c';ctx.fillRect(p[0]-sw/2,p[1]-sh/2,sw,sh)}
const o=point(state.objective.position);ctx.strokeStyle='#c2ae7188';ctx.setLineDash([4,5]);ctx.beginPath();ctx.arc(...o,state.objective.radius/(b[2]-b[0])*w,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#c2ae71';ctx.beginPath();ctx.moveTo(o[0],o[1]-7);ctx.lineTo(o[0]+6,o[1]);ctx.lineTo(o[0],o[1]+7);ctx.lineTo(o[0]-6,o[1]);ctx.fill();
for(const u of state.units){if(u.hp<=0)continue;const p=point(u.position);ctx.fillStyle=colors[u.faction];if(u.faction===team&&u.state==='move'){const g=point(u.goal);ctx.strokeStyle=colors[u.faction]+'50';ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...g);ctx.stroke()}if(u.kind==='tank')ctx.fillRect(p[0]-8,p[1]-11,16,22);else{ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill()}if(u.selected){ctx.strokeStyle='#e1d6a9';ctx.beginPath();ctx.arc(...p,9,0,Math.PI*2);ctx.stroke()}}
}
function render(){if(!state.units)return;$("#levelSelect").value=state.map_index??0;factions();drawMap();$('#clock').textContent=clock(state.time);$('#population').textContent=state.units.filter(u=>u.hp>0).length+' 单位';const d=state.decisions[team]||{};const squad=state.tactical?.squads?.[team];$('#tacticalPhase').textContent=phases[squad?.phase]||'外部指令';$('#squadDetail').textContent=squad?`队长 ${squad.leader} · 推进者 ${squad.mover||'无'} · 可提供火力 ${squad.support_ids?.length||0} 人`:'由玩家或 Agent 指挥';$('#decision').textContent=state.winner?state.winner==='draw'?'战斗结束 · 平局':names[state.winner]+'获胜':actions[d.action]||'等待战术评估';$('#reason').textContent=d.reason||'AI 将在首个决策周期分配行动。';$('#verified').textContent=live?'● 状态已同步':'○ 状态已过期';$('#source').textContent=modes[state.control[team]];$('#tick').textContent=state.tick;$('#shots').textContent=state.shots;$('#score').textContent=Math.floor(state.scores[team])+' / '+state.objective.score_to_win;$('#teamLabel').textContent=team.toUpperCase();$('#navrev').textContent='NAV '+state.navigation_revision;$('#reserve').textContent=Object.keys(state.reservations).length+' 站位预约';$('#candidates').innerHTML=(d.candidates||[]).map(c=>`<div class="candidate">${actions[c.action]}<span>${Number(c.score).toFixed(2)}</span></div>`).join('')||`<p class="caption">${squad?'协调器按战术条件切换阶段，无模型概率评分。':'当前由外部指令控制。'}</p>`;$('#units').innerHTML=state.units.filter(u=>u.faction===team).map(u=>`<div class="unit"><span style="color:${colors[team]}">${u.kind==='tank'?'▰':'◆'} ${u.id}</span><div>${u.weapon_name||''} · ${states[u.state]||u.state}<small> · ${u.in_cover?'掩体内':stances[u.cqb_stance]||''}</small><div class="caption">${roles[u.tactical_role]||''} · ${orders[u.order_mode]||u.order_mode||''}${u.kind==='tank'?' · 炮塔 '+Math.round(u.turret_yaw*180/Math.PI)+'°':''}</div><div class="bar"><i style="width:${100*u.hp/u.max_hp}%;background:${colors[team]}"></i></div></div><b>${Math.ceil(u.hp)} HP<br><small>${u.kind==='tank'?'炮弹':u.ammo+' 发'}</small></b></div>`).join('');$('#events').innerHTML=state.events.slice(0,12).map(e=>`<div class="event"><time>${clock(e.time)}</time><span>${escapeHTML(e.text)}</span></div>`).join('');$('#pause').textContent=state.paused?'继续':'暂停';$('#tank').disabled=state.tank_spawned;$('#phase').textContent=state.winner?'04 / 战斗结束':state.tank_spawned?'03 / 阵地后方，坦克抵达':state.time>8?'02 / 桌面上的掩护与交战':'01 / 办公桌上的小小前线';$('#stage2').classList.toggle('on',state.time>8);$('#stage3').classList.toggle('on',state.tank_spawned);$('#fps').textContent=state.fps+' FPS';$$('[data-camera]').forEach(el=>el.classList.toggle('active',el.dataset.camera===state.camera));}
async function poll(){try{const r=await fetch('/api/state');const d=await r.json();live=d.engine_live;state=d.state;$('#led').classList.toggle('live',live);$('#connection').textContent=live?'引擎实时连接':d.age_seconds?'引擎已离线 · 保留最后状态':'等待游戏引擎';if(pendingId){const result=await (await fetch('/api/result/'+pendingId)).json();if('accepted'in result){$('#receipt').textContent=result.accepted?'✓ 已由引擎执行':'× 被引擎拒绝：'+result.message;toast(result.accepted?'已执行':'拒绝：'+result.message);pendingId=null}}render()}catch(e){live=false;$('#connection').textContent='控制服务未连接'}finally{setTimeout(poll,350)}}
$$('[data-action]').forEach(el=>el.onclick=()=>command({action:el.dataset.action}));$$('[data-camera]').forEach(el=>el.onclick=()=>command({action:'camera',mode:el.dataset.camera}));$('#auto').onclick=()=>command({action:'control',mode:'game_ai'});$('#pause').onclick=()=>command({action:'pause',value:!state.paused});$('#tank').onclick=()=>command({action:'reinforce'});$('#reset').onclick=()=>command({action:'reset'});$('#speed').onchange=e=>command({action:'speed',value:Number(e.target.value)});$$('[data-param]').forEach(el=>{el.oninput=()=>el.nextElementSibling.value=el.value;el.onchange=()=>command({action:'config',key:el.dataset.param,value:Number(el.value)})});$('#map').onclick=e=>{if(!live||!state.bounds)return;const r=e.currentTarget.getBoundingClientRect(),b=state.bounds;command({action:'move',position:[b[0]+(e.clientX-r.left)/r.width*(b[2]-b[0]),b[1]+(e.clientY-r.top)/r.height*(b[3]-b[1])]})};$('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='deskfront-state.json';a.click();URL.revokeObjectURL(url)};poll();

$("#levelSelect").onchange=e=>command({action:"map",index:Number(e.target.value)});
$("#weaponSelect").onchange=e=>command({action:"equip",weapon:e.target.value});
